//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ordinacija.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordinacija
    {
        public string Naziv { get; set; }
        public string Stomatolog { get; set; }
        public string Administrator { get; set; }
        public System.TimeSpan RadnoVrijemeOD { get; set; }
        public System.TimeSpan RadnoVrijemeDO { get; set; }
        public string Telefon { get; set; }
        public string Adresa { get; set; }
    }
}
